### ISSUE TITLE
Stakeholders not saving to backend

### ISSUE THREAD

**Issue by karrla** [toladata/TolaActivity#1034] opened 2018-02-22 14:06 UTC
### Current behavior
Stakeholders not saving to backend

see https://github.com/Humanitec/TolaDataV2/issues/938

### Expected behavior
Stakeholders should save to backend

**Comment by Menda** [comment] 2018-02-23 10:08
Hi @karrla I can't reproduce it on Staging. I am ProgramAdmin, and if I add a Stakeholder and reload the page it is persisted.

**Comment by jefmoura** [comment] 2018-02-23 13:03
It's working. Probably, it was fixed with the @wceolin merge. @karrla

**Closed** 2018-02-28 11:37 UTC
Labels: bug, showstopper
